// <auto-generated />
using EFCore_101.App_Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_101.App_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230805092024_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Turkish_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_101.App_Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Population")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 887.7m,
                            CityName = "Berlin",
                            Population = 3460725m,
                            StateId = 3
                        },
                        new
                        {
                            Id = 2,
                            Area = 755.16m,
                            CityName = "Hamburg",
                            Population = 1786448m,
                            StateId = 6
                        },
                        new
                        {
                            Id = 3,
                            Area = 310.69m,
                            CityName = "Munich / Munchen",
                            Population = 1353186m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 4,
                            Area = 405.17m,
                            CityName = "Cologne / Koln",
                            Population = 1007119m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 5,
                            Area = 248.31m,
                            CityName = "Frankfurt am Main",
                            Population = 679664m,
                            StateId = 7
                        },
                        new
                        {
                            Id = 6,
                            Area = 207.35m,
                            CityName = "Stuttgart",
                            Population = 606588m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 7,
                            Area = 217.22m,
                            CityName = "Dusseldorf",
                            Population = 588735m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 8,
                            Area = 280.71m,
                            CityName = "Dortmund",
                            Population = 580444m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 9,
                            Area = 210.32m,
                            CityName = "Essen",
                            Population = 574635m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 10,
                            Area = 325.42m,
                            CityName = "Bremen",
                            Population = 547340m,
                            StateId = 5
                        },
                        new
                        {
                            Id = 11,
                            Area = 328.31m,
                            CityName = "Dresden",
                            Population = 523058m,
                            StateId = 13
                        },
                        new
                        {
                            Id = 12,
                            Area = 297.36m,
                            CityName = "Leipzig",
                            Population = 522883m,
                            StateId = 13
                        },
                        new
                        {
                            Id = 13,
                            Area = 204.14m,
                            CityName = "Hanover / Hannover",
                            Population = 522686m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 14,
                            Area = 186.38m,
                            CityName = "Nuremberg / Nurnberg",
                            Population = 505664m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 15,
                            Area = 232.83m,
                            CityName = "Duisburg",
                            Population = 489599m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 16,
                            Area = 145.66m,
                            CityName = "Bochum",
                            Population = 374737m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 17,
                            Area = 168.39m,
                            CityName = "Wuppertal",
                            Population = 349721m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 18,
                            Area = 141.22m,
                            CityName = "Bonn",
                            Population = 324899m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 19,
                            Area = 257.92m,
                            CityName = "Bielefeld",
                            Population = 323270m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 20,
                            Area = 144.96m,
                            CityName = "Mannheim",
                            Population = 313174m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 21,
                            Area = 173.46m,
                            CityName = "Karlsruhe",
                            Population = 294761m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 22,
                            Area = 302.96m,
                            CityName = "Munster",
                            Population = 279803m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 23,
                            Area = 203.93m,
                            CityName = "Wiesbaden",
                            Population = 275976m,
                            StateId = 7
                        },
                        new
                        {
                            Id = 24,
                            Area = 146.84m,
                            CityName = "Augsburg",
                            Population = 264708m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 25,
                            Area = 160.84m,
                            CityName = "Aachen",
                            Population = 258664m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 26,
                            Area = 170.45m,
                            CityName = "Monchengladbach",
                            Population = 257993m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 27,
                            Area = 104.94m,
                            CityName = "Gelsenkirchen",
                            Population = 257981m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 28,
                            Area = 192.15m,
                            CityName = "Brunswick / Braunschweig",
                            Population = 248867m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 29,
                            Area = 220.84m,
                            CityName = "Chemnitz",
                            Population = 243248m,
                            StateId = 13
                        },
                        new
                        {
                            Id = 30,
                            Area = 118.65m,
                            CityName = "Kiel",
                            Population = 239526m,
                            StateId = 15
                        },
                        new
                        {
                            Id = 31,
                            Area = 137.75m,
                            CityName = "Krefeld",
                            Population = 235076m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 32,
                            Area = 135.02m,
                            CityName = "Halle",
                            Population = 232963m,
                            StateId = 14
                        },
                        new
                        {
                            Id = 33,
                            Area = 200.99m,
                            CityName = "Magdeburg",
                            Population = 231549m,
                            StateId = 14
                        },
                        new
                        {
                            Id = 34,
                            Area = 153.06m,
                            CityName = "Freiburg",
                            Population = 224191m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 35,
                            Area = 77.11m,
                            CityName = "Oberhausen",
                            Population = 212945m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 36,
                            Area = 214.21m,
                            CityName = "Lübeck",
                            Population = 210232m,
                            StateId = 15
                        },
                        new
                        {
                            Id = 37,
                            Area = 269.14m,
                            CityName = "Erfurt",
                            Population = 204994m,
                            StateId = 16
                        },
                        new
                        {
                            Id = 38,
                            Area = 181.26m,
                            CityName = "Rostock",
                            Population = 202735m,
                            StateId = 9
                        },
                        new
                        {
                            Id = 39,
                            Area = 97.74m,
                            CityName = "Mainz",
                            Population = 199237m,
                            StateId = 11
                        },
                        new
                        {
                            Id = 40,
                            Area = 106.78m,
                            CityName = "Kassel",
                            Population = 195530m,
                            StateId = 7
                        },
                        new
                        {
                            Id = 41,
                            Area = 160.35m,
                            CityName = "Hagen",
                            Population = 188529m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 42,
                            Area = 226.25m,
                            CityName = "Hamm",
                            Population = 181783m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 43,
                            Area = 167.09m,
                            CityName = "Saarbrucken",
                            Population = 175741m,
                            StateId = 12
                        },
                        new
                        {
                            Id = 44,
                            Area = 91.29m,
                            CityName = "Mulheim",
                            Population = 167344m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 45,
                            Area = 51.41m,
                            CityName = "Herne",
                            Population = 164762m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 46,
                            Area = 77.55m,
                            CityName = "Ludwigshafen",
                            Population = 164177m,
                            StateId = 11
                        },
                        new
                        {
                            Id = 47,
                            Area = 119.8m,
                            CityName = "Osnabruck",
                            Population = 164119m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 48,
                            Area = 102.98m,
                            CityName = "Oldenburg",
                            Population = 162173m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 49,
                            Area = 78.87m,
                            CityName = "Leverkusen",
                            Population = 160772m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 50,
                            Area = 89.54m,
                            CityName = "Solingen",
                            Population = 159927m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 51,
                            Area = 187.53m,
                            CityName = "Potsdam",
                            Population = 156906m,
                            StateId = 4
                        },
                        new
                        {
                            Id = 52,
                            Area = 99.53m,
                            CityName = "Neuss",
                            Population = 151388m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 53,
                            Area = 108.83m,
                            CityName = "Heidelberg",
                            Population = 147312m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 54,
                            Area = 179.51m,
                            CityName = "Paderborn",
                            Population = 146283m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 55,
                            Area = 122.09m,
                            CityName = "Darmstadt",
                            Population = 144402m,
                            StateId = 7
                        },
                        new
                        {
                            Id = 56,
                            Area = 80.7m,
                            CityName = "Regensburg",
                            Population = 135520m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 57,
                            Area = 87.63m,
                            CityName = "Wurzburg",
                            Population = 133799m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 58,
                            Area = 133.37m,
                            CityName = "Ingolstadt",
                            Population = 125088m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 59,
                            Area = 99.88m,
                            CityName = "Heilbronn",
                            Population = 122879m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 60,
                            Area = 118.69m,
                            CityName = "Ulm",
                            Population = 122801m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 61,
                            Area = 204.05m,
                            CityName = "Wolfsburg",
                            Population = 121451m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 62,
                            Area = 116.89m,
                            CityName = "Gottingen",
                            Population = 121060m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 63,
                            Area = 44.89m,
                            CityName = "Offenbach",
                            Population = 120435m,
                            StateId = 7
                        },
                        new
                        {
                            Id = 64,
                            Area = 98m,
                            CityName = "Pforzheim",
                            Population = 119781m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 65,
                            Area = 66.43m,
                            CityName = "Recklinghausen",
                            Population = 118365m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 66,
                            Area = 100.61m,
                            CityName = "Bottrop",
                            Population = 116771m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 67,
                            Area = 63.35m,
                            CityName = "Furth",
                            Population = 114628m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 68,
                            Area = 93.82m,
                            CityName = "Bremerhaven",
                            Population = 113366m,
                            StateId = 5
                        },
                        new
                        {
                            Id = 69,
                            Area = 87.06m,
                            CityName = "Reutlingen",
                            Population = 112484m,
                            StateId = 1
                        },
                        new
                        {
                            Id = 70,
                            Area = 74.6m,
                            CityName = "Remscheid",
                            Population = 110563m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 71,
                            Area = 105.05m,
                            CityName = "Koblenz",
                            Population = 106417m,
                            StateId = 11
                        },
                        new
                        {
                            Id = 72,
                            Area = 83.11m,
                            CityName = "Bergisch Gladbach",
                            Population = 105723m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 73,
                            Area = 76.95m,
                            CityName = "Erlangen",
                            Population = 105629m,
                            StateId = 2
                        },
                        new
                        {
                            Id = 74,
                            Area = 67.69m,
                            CityName = "Moers",
                            Population = 105506m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 75,
                            Area = 117.13m,
                            CityName = "Trier",
                            Population = 105260m,
                            StateId = 11
                        },
                        new
                        {
                            Id = 76,
                            Area = 114.47m,
                            CityName = "Jena",
                            Population = 105129m,
                            StateId = 16
                        },
                        new
                        {
                            Id = 77,
                            Area = 114.67m,
                            CityName = "Siegen",
                            Population = 103424m,
                            StateId = 10
                        },
                        new
                        {
                            Id = 78,
                            Area = 92.18m,
                            CityName = "Hildesheim",
                            Population = 102794m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 79,
                            Area = 223.91m,
                            CityName = "Salzgitter",
                            Population = 102394m,
                            StateId = 8
                        },
                        new
                        {
                            Id = 80,
                            Area = 164.29m,
                            CityName = "Cottbus",
                            Population = 102091m,
                            StateId = 4
                        });
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.IL", b =>
                {
                    b.Property<string>("IlKod")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlKod");

                    b.HasIndex("IlKod")
                        .IsUnique();

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.ILCE", b =>
                {
                    b.Property<string>("IlceKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IlKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlceKod");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.MAHALLE", b =>
                {
                    b.Property<string>("MahalleKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IlKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlceKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SbbKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MahalleKod");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.SBB", b =>
                {
                    b.Property<string>("SbbKod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IlKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlceKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemtBucakBelde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SbbKod");

                    b.ToTable("SBBler");
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StateName = "Baden-Wurttemberg"
                        },
                        new
                        {
                            Id = 2,
                            StateName = "Bavaria"
                        },
                        new
                        {
                            Id = 3,
                            StateName = "Berlin"
                        },
                        new
                        {
                            Id = 4,
                            StateName = "Brandenburg"
                        },
                        new
                        {
                            Id = 5,
                            StateName = "Bremen"
                        },
                        new
                        {
                            Id = 6,
                            StateName = "Hamburg"
                        },
                        new
                        {
                            Id = 7,
                            StateName = "Hesse"
                        },
                        new
                        {
                            Id = 8,
                            StateName = "Lower Saxony"
                        },
                        new
                        {
                            Id = 9,
                            StateName = "Mecklenburg-Vorpommern"
                        },
                        new
                        {
                            Id = 10,
                            StateName = "North Rhine-Westphalia"
                        },
                        new
                        {
                            Id = 11,
                            StateName = "Rhineland-Palatinate"
                        },
                        new
                        {
                            Id = 12,
                            StateName = "Saarland"
                        },
                        new
                        {
                            Id = 13,
                            StateName = "Saxony"
                        },
                        new
                        {
                            Id = 14,
                            StateName = "Saxony-Anhalt"
                        },
                        new
                        {
                            Id = 15,
                            StateName = "Schleswig-Holstein"
                        },
                        new
                        {
                            Id = 16,
                            StateName = "Thuringia"
                        });
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.City", b =>
                {
                    b.HasOne("EFCore_101.App_Data.Entities.State", null)
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore_101.App_Data.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
